#!/bin/sh

awk '/^\s*w/ { print  "", int($3 * 100 / 70) "% " }' /proc/net/wireless

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.

#case $BLOCK_BUTTON in
#	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
#	3) notify-send "︁ Internet module" "\- Click to connect
#x: no wifi connection
#: wifi connection with quality
#x: no ethernet
#︁: ethernet working
#" ;;
#	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

#case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
#	down) wifiicon="x" ;;
#	up) wifiicon="$(awk '/^\s*w/ { print  "", int($3 * 100 / 70) "% " }' /proc/net/wireless)" ;;
#esac

#printf "%s%s\n" "$wifiicon" "$(sed "s/down//;s/up/×︁/" /sys/class/net/e*/operstate 2>/dev/null)"
